package com.SAM2018.model;

import java.util.List;

/**
 * A class to represent a final report generated by the PCM that shows the final ranking and acceptance of a submitted paper
 * @author <a href='mailto:add5980@rit.edu'>Andrew DiStasi</a>
 */
public class Report {
    //Attributes
    private Paper subject;
    private PCC generator;
    private List<Review> pcmReviews;
    private Review pccReview;
    private AcceptanceStatus acceptanceStatus;

    /**
     * Parameterized Constructor for the Report
     * @param _subject The Paper the report is about
     * @param _generator The PCC that generated the report
     * @param _pcmReviews The list of Review objects by PCMs that support the report
     * @param _pccReview The final Review that the PCC conducted
     * @param _acceptanceStatus Whether or not the paper was accepted
     */
    public Report(Paper _subject, PCC _generator, List<Review> _pcmReviews, Review _pccReview, AcceptanceStatus _acceptanceStatus) {
        this.subject = _subject;
        this.generator = _generator;
        this.pcmReviews = _pcmReviews;
        this.pccReview = _pccReview;
        this.acceptanceStatus = _acceptanceStatus;
    }

    /**
     * Accessor for the subject attribute
     * @return subject The Paper the Report is for
     */
    public Paper getSubject() {
        return subject;
    }

    /**
     * Accessor the generator attribute
     * @return generator The PCC that created the Report
     */
    public PCC getGenerator() {
        return generator;
    }

    /**
     * Accessor for the pcmReviews Attribute
     * @return pcmReviews The List of Reviews by PCMs that support the report
     */
    public List<Review> getPcmReviews() {
        return pcmReviews;
    }

    /**
     * Accessor for the pccReview Attribute
     * @return pccReview The Review created by the PCC for the report
     */
    public Review getPccReview() {
        return pccReview;
    }

    /**
     * Accessor for the acceptanceStatus Attribute
     * @return acceptanceStatus An enum indicating if the paper was accepted
     */
    public AcceptanceStatus getAcceptanceStatus() {
        return acceptanceStatus;
    }

    /**
     * Mutator for the subject
     * @param _subject subject The paper the report is about
     */
    public void setSubject(Paper _subject) {
        this.subject = _subject;
    }

    /**
     * Mutator for generator
     * @param _generator The PCC that created the report
     */
    public void setGenerator(PCC _generator) {
        this.generator = _generator;
    }

    /**
     * Mutator for pcmReviews
     * @param _pcmReviews The List of Reviews by the PCM for the paper being reported on
     */
    public void setPcmReviews(List<Review> _pcmReviews) {
        this.pcmReviews = _pcmReviews;
    }

    /**
     * Mutator for pccReview
     * @param _pccReview The final PCC Review that accompanies the report
     */
    public void setPccReview(Review _pccReview) {
        this.pccReview = _pccReview;
    }

    /**
     * Mutator for acceptance Status
     * @param _acceptanceStatus An enum indicating if the paper was accepted
     */
    public void setAcceptanceStatus(AcceptanceStatus _acceptanceStatus) {
        this.acceptanceStatus = _acceptanceStatus;
    }

    /**
     * Helper method that formats the report information for saving to file
     * @return saveString A string prepared for writing to the file
     */
    public String saveReport() {
        String saveString = subject.getPaperID() + "|||" + generator.getUsername() + "|||" + pccReview.getRating() + "|||" + pccReview.getReviewerComments() + "|||" + acceptanceStatus + "\n";
        return saveString;
    }
}
